### ISSUE TITLE
Cannot read property 'replace'

### ISSUE THREAD

**Issue by nijikokun** [ccampbell/rainbow#102]
https://www.mashape.com/seatgeek/seatgeek

Uncaught TypeError: Cannot read property 'replace' of replacement 
Line: 578

This will probably be replaced with another library today because of this, I'm not sure what exactly is causing it, my ideas hint toward the position of the current_level is wrongly given.

**Comment by ccampbell** [comment]
This should be resolved in version 2.0 (#196) since there is no longer a global state and the processing happens in webworkers.
