### ISSUE TITLE
Rainbows Works with Python Markdown

### ISSUE THREAD

**Issue by jwogrady** [ccampbell/rainbow#105]
Making Rainbows work with Python-Markdown is surprisingly easy. You just have to enable [Markdown extra](http://packages.python.org/Markdown/extensions/extra.html) and [make this one edit to the /extensions/fenced_code.py file](https://github.com/jwogrady/bloggart/commit/431cb516584ba97625a11b267482d693b6800323). Of course, adding the stylesheets and javascript to the template still applies. I thought some of your other users might be interested. All the best.

**Comment by ccampbell** [comment]
Closing this out since it is not actually a bug
