### ISSUE TITLE
Too much recursion error in FF

### ISSUE THREAD

**Issue by VodkaBears** [ccampbell/rainbow#123]
Appears, when use with big code blocks.
Error on line 288: 
```js
var match = regex.exec(code);
```

**Comment by ccampbell** [comment]
I believe this should be working correctly in version 2.0 (#196) which I just released.

If you are still using rainbow could you give it a shot? If it is not fixed, feel free to reopen.

**Comment by ccampbell** [comment]
Okay I lied. This is still an issue. I figured it out though and have a fix I will be pushing soon
