### ISSUE TITLE
data-language="coffee" not recognized

### ISSUE THREAD

**Issue by jiyinyiyong** [ccampbell/rainbow#154]
Is that because it wasn't `"coffeescript"` that make the code unrecognizable?
But many others such as Pygmens, Highlight.js use `"coffee"` for short.
I use Rainbow at http://cirru.org/ and code marked as `"coffee"` is not highlighted.

**Comment by ccampbell** [comment]
This was fixed when the `Rainbow.addAlias` command was added.

https://github.com/ccampbell/rainbow/blob/34da2353a0c3bd4349b066b44846c1cda51aa2f7/src/language/coffeescript.js#L127
