### ISSUE TITLE
Doesn't fire when loaded asyncronous

### ISSUE THREAD

**Issue by mcguffin** [ccampbell/rainbow#156]
Looks very much like the `DOMContentLoaded` event has already being fired, when an asyncronously loaded script is executed. 

Replacing 
```
if (document.addEventListener) {
    return document.addEventListener('DOMContentLoaded', Rainbow.color, false);
}
```
with
```
document.onreadystatechange = function () {
    if ( document.readyState === "complete" ) {
        Rainbow.color();
    }
}
```
inside the self executing function at the end of `js/rainbow.js` solved this for me.

**Comment by ccampbell** [comment]
Please take a look at my comment on #167. I am going to close this ticket out as well since I don't think there is a really great solution, but I'm open to further discussion.
