### ISSUE TITLE
Building production rainbow.js fails

### ISSUE THREAD

**Issue by mikedidthis** [ccampbell/rainbow#174]
Firstly, thanks for maintaining this. 

I tried to download a production build of `rainbow.js` from the website, but received these console errors:

```
Failed to load resource: net::ERR_INVALID_RESPONSE - http://craig.is/making/rainbows/for/you
Failed to load resource: net::ERR_CACHE_MISS - http://craig.is/making/rainbows/for/you
```

And this lovely message: 

![title](http://i.imgur.com/WR045KR.png)

Its worth mentioning the development version downloads with no issues.

**Comment by ccampbell** [comment]
Oh boy!!  Thanks for reporting.  Let me take a look

**Comment by ccampbell** [comment]
Ah okay, the problem is that I by accident ended up pushing some files from the 2.0 branch even though it should still be 1.0.  Ugh...  I don't think I will be able to fix this until later tonight.

**Comment by mikedidthis** [comment]
No problem at all, it was more of a heads up!

Thanks again for the hard work!

**Comment by ccampbell** [comment]
Okay this should be working now!
