### ISSUE TITLE
How to make Rainbow.color works synchronous?

### ISSUE THREAD

**Issue by brantxiong** [ccampbell/rainbow#181]
At now, Rainbow.color works synchronous, which means when call Rainbow.color frequently, some text could not rendered properly. Is there a way to make Rainbow.color works synchronous?

**Comment by dr-dimitru** [comment]
+1

**Comment by ccampbell** [comment]
This should be resolved in version 2.0 (#196) with the `Rainbow.colorSync` function.

It is currently only possible when using via node.js
