### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by nobitagit** [ccampbell/rainbow#184]
Hi there, 
is there any plan to publish Rainbow on npm? If not would you consider it?

I have searched through issues and PRs looking for npm but couldn't find anything about it, so if I missed sorry about that. In case help is needed I can contribute on it if you like.

Cheers and thanks for making this tool.

**Comment by bjb568** [comment]
Related: https://github.com/ccampbell/rainbow/issues/7

**Comment by ccampbell** [comment]
Rainbow is now availble on NPM!

https://www.npmjs.com/package/rainbow-code
