### ISSUE TITLE
CommonJS compatibility

### ISSUE THREAD

**Issue by IngwiePhoenix** [ccampbell/rainbow#185]
Hey there.

I just found this project on the search for a smaller alternative to Highlight.js. So far, I really like how this project looks and works. However, I was pretty bummed when I noticed that it does not allow direct WebPack usage.

Looking at the code, I see that `window["Rainbow"]` is used to export the module. I'd like to propose a slight alternation to this line:

```javascript
var root = {};
if(typeof module != "undefined" && typeof module.exports == "object") {
    module.exports = root;
} else {
    window["Rainbow"] = root;
}

root = ...;
```

This would allow this project to run in WebPack - a NodeJS-like environment - and traditionaliy in the global Window object.

Kind regards, Ingwie

**Comment by ccampbell** [comment]
I am pretty sure that the 2.0 branch has this as well as some other things I just haven't gotten around to finishing it up but I suppose you could try it out

**Comment by IngwiePhoenix** [comment]
Alright. Thanks for the info, I will do so. :)
