### ISSUE TITLE
Cannot read property '41' of undefined

### ISSUE THREAD

**Issue by wordofchristian** [ccampbell/rainbow#194]
There seems to be a problem with the library simultaneously processing several code blocks at once. 

I was able to reproduce the issue here: http://codepen.io/wordofchristian/pen/vGMZVY

It gives the following error:
```
rainbow.js:577 Uncaught TypeError: Cannot read property '40' of undefined 
```

It seems that the internal `replacements` object [is getting overridden](https://github.com/ccampbell/rainbow/blob/master/js/rainbow.js#L634).

**Comment by ccampbell** [comment]
This should be resolved in version 2.0 (#196)
