### ISSUE TITLE
multiline comments not working when embedded language

### ISSUE THREAD

**Issue by DhatesCode** [ccampbell/rainbow#200]
Just started using Rainbow and I noticed if I embed languages multi-line comments don't work. Only the first line is recognized as a comment.

I'm using html as the data-language. I saw this behavior with embedded css and php when I set it up in WordPress posts. If using them on their own, multi-line comments **are** working as expected.

```css
/*---------------
sexy comment
----------------*/
```

```php
<?php
/*
sexy comment
*/
?>
```

Besides that, it works a treat. Love it.

**Comment by XeroToulouse** [comment]
Here's how I was setting up embedded stuff.

```html
<pre><code data-language="html">/*--------------
sexy comment
--------------*/
.foo { color:brown }
.bar { color:yellow }</code></pre>
```

**Comment by ccampbell** [comment]
It works fine for me. See example here:

https://jsfiddle.net/cdh0wjwy/3/

**Comment by XeroToulouse** [comment]
strange. I'll check my code and try to setup a fiddle.

**Comment by XeroToulouse** [comment]
yeah, something strange is going on. I setup a fiddle and it seems to be working, but it's broken on my test site. Maybe something in wordpress, or some plug-in, is conflicting.

I'll let you know if I find anything.

**Comment by XeroToulouse** [comment]
Hey man

I figured it out. The multi-line comments is breaking with Blender3D rainbow.linenumbers.js being used. I'll drop them a line and see if they can fix it.

**Comment by ccampbell** [comment]
Closing this out since it is not an issue with rainbow
