### ISSUE TITLE
Enhancement: preserve html attribute line breaks

### ISSUE THREAD

**Issue by kvnlnt** [ccampbell/rainbow#206]
I'm building a component pattern library. Each component's configuration is based off of a set of data attrs. Presenting example code using rainbow js is great but without the use of line breaks for the data attrs - it's a little hard to read. Here's an example to the kind of formatting I'm looking for. 

`<div` 
 &nbsp;&nbsp;&nbsp;`data-component="Validator"`
 &nbsp;&nbsp;&nbsp;`data-form="basicForm"`
 &nbsp;&nbsp;&nbsp;`data-field="firstName"`
 &nbsp;&nbsp;&nbsp;`data-validation="minLength"`
 &nbsp;&nbsp;&nbsp;`data-args="3">First name must be at least 3 chars long</div>`

Doable? Is there already a way to do this?

**Comment by StewShack** [comment]
Will this work for you?

```html
<pre><code data-language="html">&lt;div
  data-component="Validator"
  data-form="basicForm"
  data-field="firstName"
  data-validation="minLength"
  data-args="3"&gt;First name must be at least 3 chars long&lt;/div&gt;</code></pre>
```

Here is a screenshot of this code with the blackboard theme.

![div-attrs](https://cloud.githubusercontent.com/assets/376435/18978652/0a80f818-8682-11e6-9287-1b7b367b9afb.png)
