### ISSUE TITLE
Active development?

### ISSUE THREAD

**Issue by tobiastimm** [ccampbell/rainbow#227]
Is this project still alive? Would be great to see some merged pull requests.

**Comment by MikeRogers0** [comment]
I don't think it is :/

I good alternative I've been migrating over to is https://highlightjs.org/ , to use it you can pretty much do:

```
yarn add highlightjs
```

then in your code

```
$(document).ready(function() {
  $('pre code').each(function(i, block) {
    hljs.highlightBlock(block);
  });
});
```

**Comment by ccampbell** [comment]
Ya. Sorry I do not have a ton of time these days to work on open source projects, but it is certainly not dead. I just published a new version with a couple fixes today.
