### ISSUE TITLE
Rainbow.color does not work

### ISSUE THREAD

**Issue by centurianii** [ccampbell/rainbow#239]
I run the examples 1, 2 & 3 in the Readme section for `Rainbow.color` and I can see the theme or the code:
     <pre><code data-language="javascript" class="rainbow">var foo = true;</code></pre>
but no formating is applied!

Any idea? present an example at bootsnip that works!

**Comment by centurianii** [comment]
So, it seems it needs **both** files to work:
1. [rainbow.js](https://cdnjs.cloudflare.com/ajax/libs/rainbow/1.2.0/js/rainbow.min.js)

2. [generic.js](https://cdnjs.cloudflare.com/ajax/libs/rainbow/1.2.0/js/language/generic.min.js)

and _then_ any language file.

It also seems that reloading the above files the library does not function properly-I don't know why.

**Comment by ccampbell** [comment]
Depending on the language you are using, generic may be required. You can see if you use the download button on the rainbow site to build a custom package. Some will automatically include the generic patterns. 

The files *are* merged. You can simply include `rainbow.min.js` from the repo or build a custom version of rainbow from the website.
