### ISSUE TITLE
Update webworker-threads@0.7.13 to 0.7.17^

### ISSUE THREAD

**Issue by dennismuench** [ccampbell/rainbow#242]
Building webworker-threads 0.7.13 fails on node 10 (C2872: "ArrayBufferAllocator", and various other errors). This was fixed in 0.7.17 https://github.com/audreyt/node-webworker-threads/issues/189.
So updating the dependency to webworker-threads should fix the issue.

**Comment by dennismuench** [comment]
Uups

**Comment by dennismuench** [comment]
Uups

**Comment by ccampbell** [comment]
Hay happy to merge this, but are you sure it actually fixes the issue? I believe I had tried this version or maybe 0.8.0 recently with node 11.9.0 and had no luck.

See https://github.com/audreyt/node-webworker-threads/issues/193. I even have a [branch](https://github.com/ccampbell/rainbow/tree/importable-languages) of rainbow with node support disabled (and some other changes) to get around this issue.

**Comment by dennismuench** [comment]
Hay! Yes i tested it:

`npm install git+https://git@github.com/dennismuench/rainbow.git`

and it indeed solved the issue for node **10 LTS**. I don't know if the issue with node **11.9.0** is a different case.

**Comment by DemidovVladimir** [comment]
Same error with 0.7.17:
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
gyp ERR! stack     at Socket.emit (events.js:198:13)
gyp ERR! stack     at Pipe._handle.close (net.js:606:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/vladimirdemidov/.nvm/versions/node/v10.16.3/bin/node" "/Users/vladimirdemidov/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/vladimirdemidov/code/node-internals/node_modules/webworker-threads
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN internals@1.0.0 No description
npm WARN internals@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webworker-threads@0.7.17 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webworker-threads@0.7.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vladimirdemidov/.npm/_logs/2019-09-07T17_57_17_704Z-debug.log

**Comment by dsandstrom** [comment]
Related: https://github.com/audreyt/node-webworker-threads/issues/206#issuecomment-623083323
