### ISSUE TITLE
Provide a synchronous API

### ISSUE THREAD

**Issue by philc** [ccampbell/rainbow#43]
It makes sense that the API is asynchronous by default, but it would be nice to have another API which is synchronous (it returns the highlighted text and doesn't take a callback). This is particularly useful for server-side usage of Rainbow. Otherwise setTimeout gymnastics are required (see #7).

**Comment by ccampbell** [comment]
Support for node.js and `Rainbow.colorSync` was added in version 2.0 which finally was released.

```
npm install rainbow-code
```

```javascript
var rainbow = require('rainbow-code');
var highlightedCode = rainbow.colorSync('var finally = true;', 'javascript');
```
