### ISSUE TITLE
Error: Too much recursion

### ISSUE THREAD

**Issue by pockata** [ccampbell/rainbow#57]
Hello, today Rainbow threw an error: too much recursion at line 510 or sometimes at line 375!
Here's a paste of the code it ran on: http://pastie.org/4058180
There's nothing else on the page.
It only happens in Firefox 13 under Windows. In Opera 11, Chrome 19 and IE 9 it works fine..

**Comment by ccampbell** [comment]
This should be resolved in version 2.0 (#196) released today.
