### ISSUE TITLE
node.js support?

### ISSUE THREAD

**Issue by tipiirai** [ccampbell/rainbow#7]
Looks like a fine and compact syntax package. 

Any plans to support node.js so that you can do syntax hilite on the server too?

Also makes testing more easy. 

Keep up the good, minimal work!

**Comment by ccampbell** [comment]
Support for node.js and `Rainbow.colorSync` was added in version 2.0 which finally was released.

```
npm install rainbow-code
```

```javascript
var rainbow = require('rainbow-code');
var highlightedCode = rainbow.colorSync('var finally = true;', 'javascript');
```
