### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getAttribute' of null

### ISSUE THREAD

**Issue by PhilG** [ccampbell/rainbow#84]
This is what I get when using Rainbow in my actual project. I'm not using the data-language attribute but classes, and I think there is the problem.

Except for this error it's working very well! Maybe you should add a try..catch block around the problematic function, not really sure.

> Uncaught TypeError: Cannot read property 'getAttribute' of null rainbow.js:101
> _attr rainbow.js:101
> _getLanguageForBlock rainbow.js:150
> _highlightCodeBlock rainbow.js:619
> _highlightCodeBlock rainbow.js:644
> _highlightCodeBlock rainbow.js:644
> _highlightCodeBlock rainbow.js:644
> _highlightCodeBlock rainbow.js:644
> _highlightCodeBlock rainbow.js:644
> (anonymous function)

**Comment by ccampbell** [comment]
This ticket has not had any updates in a while. I just released version 2.0 of Rainbow and I have a feeling this should be resolved. If it is still not working please reopen and link me to a jsfiddle.
