### ISSUE TITLE
Maybe, contenteditable?

### ISSUE THREAD

**Issue by remaerd** [ccampbell/rainbow#99]
First of all, Thank you for your codes.

I'm working on script editor which need to do some syntax highlighting. So I try to use CodeMirror. My web app is an one page app. The minified JS file is really big: 401KB in total. If I can use rainbow + contenteditable without Codemirror. I can make it 130KB smaller, Which is a really huge deal.

Do you think it's possible to do that? None of other highlighter can do this kind of stuff.

Thank you again.

**Comment by ccampbell** [comment]
This is not something I plan on supporting natively in Rainbow, but if you have any examples of this working I would be happy to include a link in the README
